<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="groups">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="group" type="group_def" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="group_list">
        <xs:list itemType="xs:string" />
    </xs:simpleType>

    <xs:complexType name="group_def">
        <xs:simpleContent>
            <xs:extension base="group_list">
                <xs:attribute name="name" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string" />
                    </xs:simpleType>
                </xs:attribute>

                <xs:attribute name="count_hyphen_as_space" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            Since we assume space is our delimiter for entries, 
                            whenever an entry is parsed any hyphens are replaced with spaces.

                            This is specifically to account for the edge case for accessories.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean" />
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>